using System;
using System.Collections.Generic;
using System.Linq;
using Xunit;

public class FileReader{

public static List<string> GetWordsMock(){
    List<string> words = new List<string>();
     words.Add("tar");
        words.Add("arc");
        words.Add("glean");
        words.Add("stressed");
        words.Add("state");
        words.Add("elbow");
        words.Add("taste");
        words.Add("cried");
        words.Add("cider");
        words.Add("dusty");
        words.Add("pairs");
        words.Add("chin");
        words.Add("study");
        words.Add("night");
        words.Add("thing");
        words.Add("inch");
        words.Add("robed");
        words.Add("grab");
        words.Add("cat");
        words.Add("bored");
        words.Add("nerved");
        words.Add("below");
        words.Add("save");
        words.Add("vase");
        words.Add("angel");
        words.Add("car");
        words.Add("desserts");
        words.Add("rat");
        words.Add("brag");
        words.Add("act");
        words.Add("paris");
        words.Add("denver");
        words.Add("eight");
        words.Add("either");
        words.Add("election");
        words.Add("else");
        words.Add("employee");
        words.Add("end");
        words.Add("energy");
        words.Add("enjoy");
        words.Add("enough");
        words.Add("votes");
        words.Add("enter");
        words.Add("entire");
        words.Add("environment");
        words.Add("environmental");
        words.Add("especially");
        words.Add("establish");
        words.Add("even");
        words.Add("fried");
        words.Add("evening");
        words.Add("event");
        words.Add("ever");
        words.Add("stove");
        words.Add("every");
        words.Add("untied");
        words.Add("claim");
        words.Add("class");
        words.Add("fired");
        words.Add("clear");
        words.Add("clearly");
        words.Add("close");
        words.Add("coach");
        words.Add("cold");
        words.Add("collection");
        words.Add("college");
        words.Add("color");
        words.Add("come");
        words.Add("dog");
        words.Add("commercial");
        words.Add("common");
        words.Add("head");
        words.Add("health");
        words.Add("hear");
        words.Add("heart");
        words.Add("heat");
        words.Add("wolf");
        words.Add("heavy");
        words.Add("help");
        words.Add("her");
        words.Add("here");
        words.Add("herself");
        words.Add("high");
        words.Add("him");
        words.Add("himself");
        words.Add("united");
        words.Add("god");
        words.Add("teacher");
        words.Add("flow");
        words.Add("cheater");
        words.Add("break");
        words.Add("rebuild");
        words.Add("dice");
        words.Add("senator");
        words.Add("kitchen");
        words.Add("treason");
        words.Add("thicken");
        words.Add("builder");
        words.Add("baker");
        words.Add("iced");
        return words;


}

}